#!/bin/bash
set -x
chown_if_exists()
{
	path="${@:${#@}}"
	if [ -e "$path" ]; then
		chown $@
	else
		echo "skipping, path does not exist: $path"
	fi
}
if id -u git; then
	chown_if_exists -R git:git /var/opt/gitlab/.ssh
	chown_if_exists -R git:git /var/opt/gitlab/.gitconfig
	chown_if_exists -R git:git /var/opt/gitlab/git-data
	chown_if_exists -R git:git /var/opt/gitlab/gitlab-ci/builds
	chown_if_exists -R git:git /var/opt/gitlab/gitlab-rails
	chown_if_exists -R git:git /var/opt/gitlab/gitlab-shell
	if id -g gitlab-www; then
		chown_if_exists -R git:gitlab-www /var/opt/gitlab/gitlab-workhorse
	fi
	chown_if_exists git /var/opt/gitlab/gitlab-workhorse
	chown_if_exists git /var/log/gitlab/gitlab-rails
	chown_if_exists git /var/log/gitlab/gitlab-shell
	chown_if_exists git /var/log/gitlab/sidekiq
	chown_if_exists git /var/log/gitlab/unicorn
	chown_if_exists -R git:git /var/log/gitlab/gitlab-rails/*.log
	chown_if_exists -R git:git /var/log/gitlab/gitlab-shell/*.log
	chown_if_exists -R git:git /var/log/gitlab/unicorn/*.log
fi
if id -u gitlab-www; then
	chown_if_exists -R gitlab-www:gitlab-www /var/opt/gitlab/nginx/*_temp
	chown_if_exists -R gitlab-www:gitlab-www /var/opt/gitlab/nginx/*_cache
fi
if id -u gitlab-psql; then
	chown_if_exists -R gitlab-psql:gitlab-psql /var/opt/gitlab/postgresql
	chown_if_exists gitlab-psql /var/log/gitlab/postgresql
fi
if id -u gitlab-prometheus; then
	chown_if_exists -R gitlab-prometheus:gitlab-prometheus /var/opt/gitlab/prometheus
	chown_if_exists gitlab-prometheus /var/log/gitlab/prometheus
fi
if id -u gitlab-redis; then
	chown_if_exists -R gitlab-redis:gitlab-redis /var/opt/gitlab/redis
	if id -g git ; then
		chown_if_exists gitlab-redis:git /var/opt/gitlab/redis
	fi
	chown_if_exists gitlab-redis /var/log/gitlab/redis
fi
if id -u registry; then
    chown_if_exists -R registry:git /var/opt/gitlab/gitlab-rails/shared/registry
fi
